<h1>Клиническая патогистология</h1>
<ul>
<li><a href="pdf/pat_hyst_3_lab_diag.pdf" target="_blank">Тематический и календарный план лекций на осенний период&nbsp;3 курс</a></li>
<li><a href="pdf/pat_hyst_lz_3_lab_diag.pdf" target="_blank">Тематический и календарный план лабораторных занятий на осенний период&nbsp;3 курс</a></li>
<li><a href="pdf/pat_hyst_5_lab_diag.pdf" target="_blank">Тематический и календарный план лекций на осенний период&nbsp;5 курс</a></li>
<li><a href="pdf/pat_hyst_lz_5_lab_diag.pdf" target="_blank">Тематический и календарный план лабораторных занятий на осенний период&nbsp;5 курс</a></li>
<li><a href="pdf/patohyst_pnd_3_course.pdf" target="_blank">Рабочая программа учебной дисциплины (3 курс)</a></li>
<li><a href="pdf/patohyst_pnd_5_course.pdf" target="_blank">Рабочая программа учебной дисциплины (5 курс)</a></li>
<li><a href="pdf/patohyst_literature.pdf" target="_blank">Список рекомендованной литературы</a></li>
<li><a href="pdf/pat_hyst_qwest.pdf" target="_blank">Перечень вопросов к итоговому модульному контролю</a></li>
</ul>