<h1>I Науково-практична інтернет-конференція з міжнародною участю "Механізми розвитку патологічних процесів і хвороб та їхня фармакологічна корекція"</h1>
<ul>
<li><a href="pdf/Inform%20list.pdf" target="_blank">Інформаційне повідомлення інтернет-конференції</a></li>
<li><a href="pdf/Program%20conf.%2018.10.2018.pdf" target="_blank">Програма Конференції</a></li>
<li><a href="pdf/Materiali%20konf.pdf" target="_blank">Збірник матеріалів Конференції</a></li>
<li><a href="pdf/Sertificat.pdf" target="_blank">Сертифікат учасника Конференції</a></li>
</ul>