<h1>Патологічна фізіологія</h1>
<h3>Робоча програма навчальної дисципліни:</h3>
<ul>
<li><a href="pdf/pat_phy_pnd_pharmacy.pdf" target="_blank">для спеціальності 7.110201 "Фармація"</a>;</li>
<li><a href="pdf/pat_phy_pnd_pharmacy_4.0.pdf">для спеціальності 226 Фармація, промислова фармація (4,0) 1 курс;</a></li>
<li><a href="pdf/pat_phy_pnd_pharmacy_4.0%20med.pdf">для спеціальності 226 Фармація, промислова фармація (4,0 мед) 2 курс;</a></li>
<li><a href="pdf/pat_phy_pnd_lab_diag.pdf" target="_blank">для спеціальності 6.120102 "Лабораторна діагностика"&nbsp;(4.0);</a></li>
<li><a href="pdf/pat_phy_pnd_lab_diag_add.pdf" target="_blank">зміни та доповнення до робочої програми для спеціальності 6.120102 "Лабораторна діагностика"&nbsp;(3.0) (2.0)</a></li>
</ul>
<h3>Тематичний та календарний план лекцій, семінарських та практичних занять на осінній семестр 2017-2018 н.р.:</h3>
<ul>
<li><a href="pdf/Pharmacy_autum.pdf" target="_blank">для спеціальності "Фармація";</a></li>
<li><a href="pdf/Pharmacy%20(4.0med)%20autum.pdf" target="_blank">для спеціальності "Фармація" (4,0 мед)</a>;&nbsp;</li>
<li><a href="pdf/pat_phyz_tem_plan_tpkz_1.pdf" target="_blank">для спеціальності "ТПКЗ";</a></li>
<li><a href="pdf/pat_phyz_tem_plan_ld_1.pdf" target="_blank">для спеціальності "Лабораторна діагностика" (4,0)</a></li>
</ul>
<h3>&nbsp;Тематичний та календарний план лекцій, семінарських та практичних занять на весняний семестр 2017-2018 н.р.:</h3>
<ul>
<li><a href="pdf/pat_phyz_tem_plan_farm_1.pdf" target="_blank">для спеціальності "Фармація";</a></li>
<li><a href="pdf/Pharmacy%20(4.0med)%20autum.pdf" target="_blank">для спеціальності "Фармація" (4,0 фарм.)</a>;&nbsp;</li>
<li><a href="pdf/pat_phyz_tem_plan_tpkz_2.pdf" target="_blank">для спеціальності "ТПКЗ";</a></li>
<li><a href="pdf/pat_phyz_tem_plan_ld_1.pdf" target="_blank">для спеціальності "Лабораторна діагностика" (4,0)</a>;</li>
<li><a href="pdf/pat_phyz_tem_plan_ld_3.pdf">для спеціальності "Лабораторна діагностика" (3,0);</a></li>
<li><a href="pdf/pat_phys_ld_2.0.pdf" target="_blank">для спеціальності "Лабораторна діагностика" (2,0)</a></li>
</ul>
<h3>Методичні рекомендації до організації самостійної роботи студентів</h3>
<ul>
<li><a href="pdf/Individual%20work.pdf" target="_blank">Питання для самостійної підготовки</a>&nbsp;для спеціальності "Фармація";</li>
<li><a href="pdf/Individual%20work%20(4.0%20med).pdf" target="_blank">Питання для самостійної підготовки&nbsp;для спеціальності "Фармація" (4,0 мед)</a></li>
</ul>
<h3>Перелік питань для підсумкового модульного контролю</h3>
<ul>
<li><a href="pdf/pat_phy_module_1_quest.pdf" target="_blank">Питання для підсумкового модульного контролю 1</a></li>
<li><a href="pdf/pat_phy_module_2_quest.pdf" target="_blank">Питання для підсумкового модульного контролю 2</a></li>
</ul>
<h3>Перелік рекомендованої літератури</h3>
<ul>
<li><a href="pdf/pat_phy_literature.pdf" target="_blank">Перелік рекомендованої літератури</a></li>
</ul>