<h1>Патофізіологія хвороб цивілізації</h1>
<p><a href="https://www.youtube.com/watch?v=RoBQHSHmRnA&amp;feature=youtu.be" target="_blank">Аудіопрезентація вибіркової дисципліни</a></p>
<p><a href="pdf/pat_phy_civ_dis.pdf" target="_blank">Робоча програма навчальної дисципліни</a></p>
<p><a href="pdf/pat_phy_civ_dis_CP.pdf" target="_blank">Календарний та тематичний план лекцій і семінарських занять&nbsp;</a></p>
<p>&nbsp;</p>